name = "portfolio"
main = "functions/[[path]].js"
compatibility_date = "2024-06-03"
compatibility_flags = ["nodejs_compat"]

[build]
upload = { format = "service-worker", dir = "./build/client" }

kv_namespaces = [
  { id = "MY_KV", binding = "MY_KV" }
]
