name = "portfolio"
main = "worker.js"
compatibility_date = "2024-06-03"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
EMAILJS_SERVICE_ID = "service_3cqfs13"
EMAILJS_TEMPLATE_ID = "template_v4jikai"
EMAILJS_PUBLIC_KEY = "_Ya88Lmr8EK5VfPFm"
SESSION_SECRET = "v@dant01!"
